---
title: "Open Policing Project in for Wichita, Kansas"
author: "Paige Eichkorn"
output:  html_document
---

## Setup

First, let's load the necessary libraries and data that will allow us to
begin our investigation!

```{r setup, message=FALSE,  warning=FALSE}
## Libraries to include
library(tidyverse)
library(lubridate)


## Load the data
# Replace the path below with the path to where your data lives
data_path <- "https://datajournalism.tech/wp-content/uploads/2019/10/wichita.csv"
stops <- read_csv(data_path)

# Additional data and fixed values we'll be using
population_2016 <- tibble(
  subject_race = c(
    "asian/pacific islander", "black", "hispanic", "other/unknown","white"
  ),
  num_people = c(19294, 42485, 65090, 16686, 245499)
) %>% 
  mutate(subject_race = as.factor(subject_race))

center_lat <- 37.689789
center_lng <- -97.322720
```

```{r}
colnames(stops)
nrow(stops)
str(stops)
summary(stops)
```

```{r}

stops %>% 
  group_by(subject_race) %>% 
  count(subject_race) %>% 
  mutate(prop = n / sum(n))
```

``` {r}
actually <- stops %>% 
count(subject_race) %>% 
left_join(population_2016,
by = "subject_race") %>% 
mutate(stop_rate = n/num_people)
```

```{r bar-chart}

bar <- ggplot(actually,
       aes(x=reorder(subject_race, stop_rate), y=stop_rate))+
  geom_bar(stat="identity", 
           position="identity", 
           fill="red")+
  geom_hline(yintercept = 0) +
  labs(title="Stopped Drivers by Race",
       subtitle = "African American drivers got stopped the most in the city of Wichita Kansas",
       caption = "Source: Stanford University")+
  coord_flip()

bar
```